### PR TITLE
Django3 related changes

### PR DESCRIPTION
**Pull request by atodorov**

### CODE REVIEW

**Comment by pauricthelodger** [comment]
@atodorov, could you remove the python2 testing while you're at it? Might as well start the year off with a bang! =)

@jordiecometrica, do you agree?

**Comment by jordiecometrica** [comment]
I'd like to keep the Python 2 testing for as long as it passes. If there's no reason to remove backwards compat, let's not remove it.

**Comment by pauricthelodger** [comment]
I'd prefer to remove it since python2.7 is EOL now and backwards compat with that it just adds more admin onto us? A major version in the release could be used as a good way of indicating the break.

This doesn't update the code so still gives people time to update if they choose, just that we're not bughunting against it any more.

Also @atodorov already updated the PR for it.

**Comment by jordiecometrica** [comment]
I say we keep it *until* it adds more admin to us. If we just keep the tests until they break, then we'll know when it's time to formally remove Python 2 support. Removing the testing right now only serves to keep us uninformed.

**Comment by atodorov** [comment]
@jordiecometrica thanks for the timely reaction. Do you mind pushing a new version to PyPI. It's not urgent but I'd like to migrate to Django 3 and prefer less warnings if possible.

**Comment by jordiecometrica** [comment]
Yes, I'm working on a new release right now.

**Comment by jordiecometrica** [comment]
There you go: https://pypi.org/project/django-vinaigrette/#history

**Pull request merged**
